# Generated by Django 5.1.3 on 2026-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Words',
            },
        ),
    ]
