# Generated by Django 5.1.3 on 2026-04-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typing_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='word_len',
            new_name='word_count',
        ),
    ]
