# Generated by Django 5.1.3 on 2026-04-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_test', '0002_wordset'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='set_code',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
