# Generated by Django 5.1.3 on 2026-04-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typing_test', '0003_wordset_set_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words',
        ),
        migrations.DeleteModel(
            name='WordSet',
        ),
    ]
