# Generated by Django 5.1.3 on 2026-04-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typing_test', '0004_delete_words_delete_wordset'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_code', models.CharField(max_length=100)),
                ('set_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Word Sets',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('word_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_test.wordset')),
            ],
            options={
                'verbose_name_plural': 'Words',
            },
        ),
    ]
