# Generated by Django 4.0.6 on 2025-10-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bensite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
