# Generated by Django 4.0.6 on 2024-03-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('current_date', models.DateTimeField(verbose_name='Current Date')),
                ('current_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Current temp in f')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('prediction_date', models.DateTimeField(verbose_name='Date prediction was made')),
                ('date', models.DateTimeField(verbose_name='Date of prediction')),
                ('prediction_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temp predicted in f')),
            ],
        ),
    ]
