# Generated by Django 4.0.6 on 2024-03-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherPredictions',
            new_name='WeatherPrediction',
        ),
    ]
