# Generated by Django 4.0.6 on 2024-03-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_weatherpredictions_weatherprediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentweather',
            options={'verbose_name_plural': 'Current weather'},
        ),
        migrations.AddField(
            model_name='currentweather',
            name='city',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentweather',
            name='statecode',
            field=models.CharField(default='na', max_length=2),
            preserve_default=False,
        ),
    ]
