# Generated by Django 4.0.6 on 2024-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_forecastdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
