# Generated by Django 4.0.6 on 2024-07-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_forecastdata_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='api_name',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='chance_of_rain',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='chance_of_snow',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='feelslike_f',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='forecast_epoch',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='forecast_made',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='precip_in',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='temp_f',
        ),
        migrations.RemoveField(
            model_name='forecastdata',
            name='will_it_rain',
        ),
    ]
