# Generated by Django 4.0.6 on 2024-07-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_forecastdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastdata',
            options={'verbose_name_plural': 'ForecastData'},
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='api_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='chance_of_rain',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='chance_of_snow',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='condition',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='feelslike_f',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='forecast_epoch',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='forecast_made',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='precip_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='temp_f',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='will_it_rain',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
