# Generated by Django 4.0.6 on 2024-07-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_forecastdata_options_forecastdata_api_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastData',
        ),
    ]
