# Generated by Django 4.0.6 on 2024-07-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_forecastdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('country_code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Weather Locations',
            },
        ),
        migrations.CreateModel(
            name='WeatherServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_ref_name', models.CharField(max_length=100)),
                ('api_display_name', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Weather Services',
            },
        ),
        migrations.AlterModelOptions(
            name='forecastdata',
            options={'verbose_name_plural': 'Forecast Data'},
        ),
    ]
