# Generated by Django 4.0.6 on 2024-07-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_weatherlocations_weatherservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('forecast_made', models.BigIntegerField()),
                ('forecast_epoch', models.BigIntegerField()),
                ('temp_f', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition', models.CharField(max_length=100)),
                ('precip_in', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feelslike_f', models.DecimalField(decimal_places=2, max_digits=5)),
                ('will_it_rain', models.IntegerField()),
                ('chance_of_rain', models.IntegerField()),
                ('chance_of_snow', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Test Forecast Data',
            },
        ),
    ]
