# Generated by Django 4.0.6 on 2024-08-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_testforecastdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('currenttime', models.IntegerField()),
                ('currenttemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('onehourbeforetime', models.IntegerField()),
                ('onehourbeforetemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('threehourbeforetime', models.IntegerField()),
                ('threehourbeforetemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sixhourbeforetime', models.IntegerField()),
                ('sixhourbeforetemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelvehourbeforetime', models.IntegerField()),
                ('twelvehourbeforetemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twentyfourhourbeforetime', models.IntegerField()),
                ('twentyfourhourbeforetemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fortyeighthourbeforetime', models.IntegerField()),
                ('fortyeighthourbeforetemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seventytwohourbeforetime', models.IntegerField()),
                ('seventyhourbeforetemp', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Forecast Pivot',
            },
        ),
        migrations.DeleteModel(
            name='CurrentWeather',
        ),
        migrations.DeleteModel(
            name='WeatherPrediction',
        ),
    ]
