# Generated by Django 4.0.6 on 2024-08-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_forecastpivot_delete_currentweather_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastpivot',
            name='currenttemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='currenttime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='fortyeighthourbeforetemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='fortyeighthourbeforetime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='onehourbeforetemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='onehourbeforetime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='seventyhourbeforetemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='seventytwohourbeforetime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='sixhourbeforetemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='sixhourbeforetime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='threehourbeforetemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='threehourbeforetime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='twelvehourbeforetemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='twelvehourbeforetime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='twentyfourhourbeforetemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastpivot',
            name='twentyfourhourbeforetime',
            field=models.IntegerField(null=True),
        ),
    ]
