# Generated by Django 4.0.6 on 2024-08-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_alter_forecastpivot_currenttemp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastpivot',
            old_name='seventyhourbeforetemp',
            new_name='seventytwohourbeforetemp',
        ),
    ]
