# Generated by Django 4.0.6 on 2024-08-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_rename_seventyhourbeforetemp_forecastpivot_seventytwohourbeforetemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlocations',
            name='accuweathercode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherlocations',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='weatherlocations',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
    ]
