# Generated by Django 4.0.6 on 2024-08-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_weatherlocations_accuweathercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherservices',
            name='days',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
