# Generated by Django 4.0.6 on 2024-09-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_alter_weatherservices_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlocations',
            name='accuweathercode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
