# Generated by Django 4.0.6 on 2024-09-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0017_alter_weatherlocations_accuweathercode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastPivot',
        ),
    ]
