# Generated by Django 4.0.6 on 2024-09-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0018_delete_forecastpivot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.IntegerField(null=True)),
                ('forecast_made', models.IntegerField(null=True)),
                ('forecast_epoch', models.IntegerField(null=True)),
                ('temp_f', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('hoursbefore', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Forecast Pivot',
            },
        ),
    ]
