# Generated by Django 4.0.6 on 2024-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0019_forecastpivot'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastpivot',
            name='currenttemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
