# Generated by Django 4.0.6 on 2024-09-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0020_forecastpivot_currenttemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursBeforeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('avg_dif', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('hoursbefore', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Hours Before Chart',
            },
        ),
    ]
