# Generated by Django 4.0.6 on 2024-09-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0021_hoursbeforechart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testforecastdata',
            name='chance_of_rain',
        ),
        migrations.RemoveField(
            model_name='testforecastdata',
            name='chance_of_snow',
        ),
        migrations.RemoveField(
            model_name='testforecastdata',
            name='precip_in',
        ),
        migrations.RemoveField(
            model_name='testforecastdata',
            name='will_it_rain',
        ),
        migrations.AddField(
            model_name='testforecastdata',
            name='precip_prob',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testforecastdata',
            name='precip_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testforecastdata',
            name='rain_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testforecastdata',
            name='snow_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
