# Generated by Django 4.0.6 on 2024-09-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0022_remove_testforecastdata_chance_of_rain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testforecastdata',
            name='chance_of_rain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testforecastdata',
            name='chance_of_snow',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testforecastdata',
            name='precip_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testforecastdata',
            name='sleet_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testforecastdata',
            name='condition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
