# Generated by Django 4.0.6 on 2024-09-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0023_testforecastdata_chance_of_rain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testforecastdata',
            name='will_it_rain',
            field=models.IntegerField(null=True),
        ),
    ]
