# Generated by Django 4.0.6 on 2024-09-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0024_testforecastdata_will_it_rain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testforecastdata',
            name='chance_of_rain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testforecastdata',
            name='chance_of_snow',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
