# Generated by Django 4.0.6 on 2024-09-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0025_alter_testforecastdata_chance_of_rain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testforecastdata',
            name='will_it_rain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
