# Generated by Django 4.0.6 on 2024-09-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0026_alter_testforecastdata_will_it_rain'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='precip_prob',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='precip_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='rain_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='sleet_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='snow_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='chance_of_rain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='chance_of_snow',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='precip_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='will_it_rain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
