# Generated by Django 4.0.6 on 2024-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0027_forecastdata_precip_prob_forecastdata_precip_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdata',
            name='condition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
