# Generated by Django 4.0.6 on 2024-09-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0028_alter_forecastdata_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherservices',
            name='daily_api_call_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
