# Generated by Django 4.0.6 on 2024-09-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0029_weatherservices_daily_api_call_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherservices',
            old_name='daily_api_call_limit',
            new_name='hourly_api_limit',
        ),
    ]
