# Generated by Django 4.0.6 on 2024-10-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0030_rename_daily_api_call_limit_weatherservices_hourly_api_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('country_code', models.CharField(max_length=3)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('accuweathercode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
