# Generated by Django 4.0.6 on 2024-10-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0031_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastpivot',
            name='city_code',
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastpivot',
            name='city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testforecastdata',
            name='city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
