# Generated by Django 4.0.6 on 2025-02-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0032_remove_forecastpivot_city_code_forecastdata_city_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('month', models.IntegerField(null=True)),
                ('avg_dif', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
