# Generated by Django 4.0.6 on 2025-02-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0033_monthlyaverage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyAverage',
            new_name='MonthlyAverageChart',
        ),
    ]
