# Generated by Django 4.0.6 on 2025-02-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0034_rename_monthlyaverage_monthlyaveragechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyaveragechart',
            name='hoursbefore',
            field=models.IntegerField(null=True),
        ),
    ]
