# Generated by Django 4.0.6 on 2025-03-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0035_monthlyaveragechart_hoursbefore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stat', models.DecimalField(decimal_places=10, max_digits=100, null=True)),
            ],
        ),
    ]
