# Generated by Django 4.0.6 on 2025-03-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0036_datastatistics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataStatistics',
            new_name='SiteStats',
        ),
    ]
