# Generated by Django 4.0.6 on 2025-03-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0037_rename_datastatistics_sitestats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestats',
            options={'verbose_name_plural': 'Site Stats'},
        ),
    ]
