# Generated by Django 4.0.6 on 2025-03-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0038_alter_sitestats_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestats',
            name='id',
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
