# Generated by Django 4.0.6 on 2025-03-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0039_remove_sitestats_id_alter_sitestats_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestats',
            name='stat',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
