# Generated by Django 4.0.6 on 2025-10-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0040_alter_sitestats_stat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyaveragechart',
            options={'verbose_name_plural': 'Monthly Average Chart'},
        ),
    ]
