# Generated by Django 5.1.3 on 2026-01-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0041_alter_monthlyaveragechart_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestForecastData',
        ),
        migrations.AddField(
            model_name='hoursbeforechart',
            name='signed_dif',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
