# Generated by Django 5.1.3 on 2026-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0042_delete_testforecastdata_hoursbeforechart_signed_dif'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastpivot',
            name='actual_precip_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='forecastpivot',
            name='actual_precip_prob',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='forecastpivot',
            name='forecasted_precip_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='forecastpivot',
            name='forecasted_precip_prob',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
