# Generated by Django 5.1.3 on 2026-02-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0043_forecastpivot_actual_precip_in_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherLocations',
        ),
    ]
