# Generated by Django 5.1.3 on 2026-02-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0044_delete_weatherlocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastpivot',
            name='actual_precip_in',
        ),
        migrations.RemoveField(
            model_name='forecastpivot',
            name='actual_precip_prob',
        ),
    ]
