# Generated by Django 5.1.3 on 2026-02-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0045_remove_forecastpivot_actual_precip_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastpivot',
            name='current_precip_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='forecastpivot',
            name='current_precip_prob',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
