# Generated by Django 5.1.3 on 2026-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0046_forecastpivot_current_precip_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPivotV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('city_name', models.CharField(max_length=100)),
                ('forecast_made', models.IntegerField(null=True)),
                ('forecast_epoch', models.IntegerField(null=True)),
                ('currenttemp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temp_f', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('hoursbefore', models.IntegerField(null=True)),
                ('forecasted_precip_in', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('forecasted_precip_prob', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('current_precip_in', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('current_precip_prob', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Forecast Pivot v2',
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('city_name', models.CharField(max_length=100)),
                ('time_epoch', models.IntegerField(null=True)),
                ('temp_f', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('current_precip_in', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('current_precip_prob', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Historical Data',
            },
        ),
    ]
