# Generated by Django 5.1.3 on 2026-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0047_forecastpivotv2_historicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipProbabilityChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('forecast_prob_bucket', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('actual_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('forecasted_count', models.IntegerField(null=True)),
                ('actual_count', models.IntegerField(null=True)),
                ('hoursbefore', models.IntegerField(null=True)),
                ('forecast_pivot_version', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Precipitation Probability Chart',
            },
        ),
    ]
