# Generated by Django 5.1.3 on 2026-02-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0048_precipprobabilitychart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrecipProbabilityChart',
            new_name='PrecipProbChart',
        ),
    ]
