# Generated by Django 5.1.3 on 2026-02-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0049_rename_precipprobabilitychart_precipprobchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursbeforechart',
            name='forecast_pivot_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monthlyaveragechart',
            name='forecast_pivot_version',
            field=models.IntegerField(null=True),
        ),
    ]
