# Generated by Django 5.1.3 on 2026-02-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0050_hoursbeforechart_forecast_pivot_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldata',
            old_name='current_precip_in',
            new_name='precip_in',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='current_precip_prob',
            new_name='precip_prob',
        ),
    ]
