# Generated by Django 5.1.3 on 2026-02-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0051_rename_current_precip_in_historicaldata_precip_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='api_name',
            field=models.CharField(default='google', max_length=100),
            preserve_default=False,
        ),
    ]
