# Generated by Django 5.1.3 on 2026-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0052_historicaldata_api_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('hoursbefore', models.IntegerField(null=True)),
                ('calibration_stat', models.IntegerField(null=True)),
                ('forecast_pivot_version', models.IntegerField(null=True)),
            ],
        ),
    ]
